<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rosbee">
  
  <!-- bottom_plate properties -->
  <property name="bottom_diameter" value="0.390" />
  <property name="bottom_height" value="0.008" />
         
  <xacro:macro name="bottom_plate" params="name parent *origin">
    
    <joint name="${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}_link"/>
      <child link="${name}_link"/>
    </joint>
    
    <link name="${name}_link">
      <visual>
      <geometry>
        <cylinder radius="${bottom_diameter/2}" length="${bottom_height}" />        
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1"/>
      </material>
    </visual>
    </link>
    
  </xacro:macro>
       
       
</robot>
